django/chc/apps/join/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('chc.apps.join.views',
    url(r'^$', 'join', name='join'),
    url(r'^signup/$', 'signup', name='join.signup'),
    url(r'^signup/thankyou/$', 'thanks', name='join.thanks'),
    url(r'^subscribe/$', 'subscribe', name='join.subscribe'),
    url(r'^subscribe/thankyou$', 'thanks', name='join.subscribe_thanks'),
    url(r'^pray/$', 'pray', name='join.pray'),
    url(r'^moreways/$', 'moreways', name='join.moreways'),
)

django/chc/urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'chc.views.home', name='home'),
    
    (r'^join/', include('chc.apps.join.urls')),
    
    url(r'^what_we_do/$', 'chc.views.what_we_do', name='what-we-do'),
    url(r'^what_we_do/projects/$', 'chc.views.projects', name='what-we-do.projects'),
    url(r'^who_we_are/$', 'chc.views.who_we_are', name='who-we-are'),
    url(r'^churches/$', 'chc.views.churches', name='churches'),
    url(r'^give/$', 'chc.views.give', name='give'),
    url(r'^media/$', 'chc.views.media', name='media'),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

django/chc/apps/join/forms.py
from django import forms

class SignupForm(forms.Form):
    fname = forms.CharField(label='First Name')
    lname = forms.CharField(label='Last Name')
    city = forms.CharField(required=False, label="City")
    state = forms.CharField(required=False, label="State / Province")
    country = forms.CharField(required=False, label = "Country")
    email = forms.EmailField(label="Email Address")
    is_pastor = forms.BooleanField(required=False, label="Check here if you are a pastor.")
    phone = forms.CharField(required=False, label="Phone")
    church_name = forms.CharField(required=False, label="Church Name")
    church_website = forms.URLField(required=False, label="Church Website")
    take_offering = forms.BooleanField(required=False, label="I'm on board. Our church will take an offering at the next crisis.")
    will_contribute = forms.BooleanField(required=False, label="I would like to contribute regularly.")
    receive_updates = forms.BooleanField(required=False, label="I would like to receive updates.", initial=True)

    def clean(self):
        cleaned_data = self.cleaned_data
        church_name = cleaned_data.get('church_name')
        is_pastor = cleaned_data.get('is_pastor')
        if is_pastor and not church_name:
            raise forms.ValidationError('Please enter a church name if you are a pastor')
        return cleaned_data

class SubscribeForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'Email Address'}))

django/chc/apps/join/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.template import RequestContext

def join(request):
	from forms import SubscribeForm

	form = SubscribeForm()
	c = { 'form': form }
	return render_to_response('join/index.html', c, context_instance=RequestContext(request))

def subscribe(request):
	from forms import SubscribeForm
	import chc.lib.MailChimp as MailChimp
	error_msgs = []

	if request.method == 'POST':
		form = SubscribeForm(request.POST)
		if form.is_valid():
			try:
				email = form.cleaned_data['email']
				merge_vars = {
					'GROUPINGS': [{'id': 705, 'groups': 'Subscribe to newsletter.'}]
				}
				MailChimp.list_subscribe(email, merge_vars)
				return HttpResponseRedirect( reverse('join.subscribe_thanks') )
			except MailChimp.MC_Exception as e:
				if e.err_code == 214: # user already subscribed
					request.session['signup.is_duplicate'] = True
					request.session['signup.email'] = form.cleaned_data['email']
					request.session['signup.mailchimp_link'] = MailChimp.extract_href(e.message)

					return HttpResponseRedirect( reverse('join.subscribe_thanks') )
				else:
					error_msgs.append("Oops! It looks like an error occurred. Please try again!")
			pass
		else:
			pass
	else:
		form = SubscribeForm()

	c = { 'form': form, 'error_msgs': error_msgs }
	return render_to_response('join/subscribe.html', c, context_instance=RequestContext(request))

def signup(request):
	from forms import SignupForm
	import chc.lib.MailChimp as MailChimp
	error_msgs = []

	if request.method == 'POST':
		form = SignupForm(request.POST)
		if form.is_valid():
			try:
				fname = form.cleaned_data['fname']
				lname = form.cleaned_data['lname']
				city = form.cleaned_data['city']
				state = form.cleaned_data['state']
				country = form.cleaned_data['country']
				phone = form.cleaned_data['phone']
				email = form.cleaned_data['email']
				church_name = form.cleaned_data['church_name']
				church_website = form.cleaned_data['church_website']
				is_pastor = form.cleaned_data['is_pastor']
				take_offering = form.cleaned_data['take_offering']
				will_contribute = form.cleaned_data['will_contribute']
				receive_updates = form.cleaned_data['receive_updates']

				groupings = []
				groups_705 = []
				if is_pastor:
					groupings.append({'id': 707, 'groups': 'Yes'})
				
				if take_offering:
					groups_705.append('Our church will take an offering at the next crisis.')
				if will_contribute:
					groups_705.append('I would like to contribute regularly.')
				if receive_updates:
					groups_705.append('Subscribe to newsletter.')
				
				groupings.append({'id': 705, 'groups': ','.join(groups_705)})

				merge_vars = {
					'FNAME': fname,
					'LNAME': lname,
					'CITY': city,
					'STATE': state,
					'COUNTRY': country,
					'PHONE': phone,
					'CHURCH': church_name,
					'WEBSITE': church_website,
					'GROUPINGS': groupings
				}
				MailChimp.list_subscribe(email, merge_vars)

				if is_pastor or will_contribute or take_offering:
					MailChimp.email_notify(is_pastor=is_pastor, will_contribute=will_contribute, 
						take_offering=take_offering, fname=fname, lname=lname, church_name=church_name,
						city=city, state=state, country=country, church_website=church_website,
						phone=phone, email=email)
				if will_contribute:
					import urllib
					donate_url = 'https://donate.churcheshelpingchurches.com/?' + urllib.urlencode({'fname': fname, 'lname': lname, 'email': email, 'phone': phone, 'city': city})
					return HttpResponseRedirect( donate_url )
				else:
					return HttpResponseRedirect( reverse('join.thanks') )
			except MailChimp.MC_Exception as e:
				if e.err_code == 214: # User already subscribed
					request.session['signup.is_duplicate'] = True
					request.session['signup.email'] = form.cleaned_data['email']
					request.session['signup.mailchimp_link'] = MailChimp.extract_href(e.message)
					
					return HttpResponseRedirect( reverse('join.thanks') )
				else:
					error_msgs.append("Oops! It looks like an error occurred. Please try again!")
		else:
			pass
	else:
		form = SignupForm(initial={'is_pastor': request.GET.get('pastor', False) })

	c = { 'form': form, 'error_msgs': error_msgs }
	return render_to_response('join/signup.html', c, context_instance=RequestContext(request))

def thanks(request):
	c = {}
	c['is_duplicate'] = request.session.get('signup.is_duplicate', False)
	c['email'] = request.session.get('signup.email', 'your email')
	c['mailchimp_link'] = request.session.get('signup.mailchimp_link', '')

	try:
		del request.session['signup.is_duplicate']
		del request.session['signup.email']
		del request.session['signup.mailchimp_link']
	except KeyError:
		pass

	return render(request, 'join/thanks.html', c)

def pray(request):
	return render(request, 'join/pray.html')

def moreways(request):
	return render(request, 'join/moreways.html')

django/chc/views.py
from django.shortcuts import render


def home(request):
	return render(request, 'home.html')

def what_we_do(request):
	return render(request, 'what-we-do/index.html')

def projects(request):
    return render(request, 'what-we-do/projects.html')

def who_we_are(request):
	return render(request, 'who-we-are.html')

def churches(request):
	return render(request, 'churches.html')

def give(request):
	return render(request, 'give.html')

def media(request):
    return render(request, 'media.html')

django/chc/templates/base.html
{% extends 'boilerplate.html' %}

{% block title %}Churches Helping Churches{% endblock %}

{% block analytics_id %}UA-XXXXX-X{% endblock %}

{% block extra_css %}{% endblock %}
{% block extra_js %}{% endblock %}

{% block header %}
<header>
	<div class="container">
		<h1 id="logo" class="ir"><a title="home" href="{% url home %}">Churches Helping Churches</a></h1>

		{% block navigation %}
		<nav>
			<h2 hidden>Main Navigation</h2>
			<ul>
			    <li>{% block nav-join %}<a href="{% url join %}" class="glow-animation">Join</a>{% endblock %}</li>
			    <li>{% block nav-what-we-do %}<a href="{% url what-we-do %}">What We Do</a>{% endblock %}</li>
			    <li>{% block nav-who-we-are %}<a href="{% url who-we-are %}">Who We Are</a>{% endblock %}</li>
			    <li>{% block nav-churches %}<a href="{% url churches %}">The Churches</a>{% endblock %}</li>
			    <li><a href="/blog">Blog</a></li> {# Blog taken care of by Wordpress #}
			    <li>{% block nav-give %}<a href="{% url give %}" class="glow-animation">Give</a>{% endblock %}</li>
			</ul>
		</nav>
		{% endblock %}

	</div>
</header>
{% endblock %}

{% block footer %}
<footer>
	<h2 hidden>Footer</h2>
	<div class="container">
		<div class="column">
			<h4>Contact Us</h4>
			<div class="vcard">
				<span class="fn n">
					<span class="given-name"></span>
					<span class="additional-name"></span>
					<span class="family-name"></span>
				</span>
				<div class="org">Churches Helping Churches</div>
				<div class="adr">
					<div class="street-address">P.O. Box 6558</div>
					<span class="locality">Elgin</span>, 
					<span class="region">IL</span><br>
					<span class="postal-code">60121-6558</span>
				</div>
				<div class="tel">1-847-398-7024 ext. 3452</div>
				<a class="email" href="mailto:information@churcheshelpingchurches.com">information@churcheshelpingchurches.com</a>
			</div>	
		</div>
		<div class="column">
			<h4>Co-Founders</h4>
			<ul class="square">
				<li><a title="James MacDonald" href="http://jamesmacdonald.com/" target="_blank">jamesmacdonald.com</a></li>
				<li><a title="Pastor Mark" href="http://pastormark.tv/" target="_blank">pastormark.tv</a></li>
			</ul>
		</div>
		<div class="column">
			<h4 class="search">Search</h4>
			<form method="get" id="searchform" action="/blog">
		        <input type="search" value="" name="s">
			</form>
			<h4>Connect With Us</h4>
			<ul class="connect">
				<li><a title="Facebook" href="https://www.facebook.com/ChurchesHelpingChurches" target="_blank" class="ir">Facebook</a></li>
				<li><a title="RSS" href="/blog/feed/" target="_blank" class="ir">RSS Feed</a></li>
				<li><a title="Twitter" href="http://twitter.com/churcheshelping" target="_blank" class="ir">Twitter</a></li>
			</ul>
		</div>

		<p id="copyright">Copyright © 2011-2012 Churches Helping Churches. All rights reserved.</p>
	</div>
</footer>
{% endblock %}

{% block content %}{% endblock %}

django/chc/templates/boilerplate.html
{% load static %}<!doctype html>
{# paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ #}
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
{% block head %}
<head>
  <meta charset="utf-8">

  {# Always force latest IE rendering engine (even in intranet) & Chrome Frame #}
  {# Remove this if you use the .htaccess #}
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{% block title %}Name your pages!{% endblock %}</title>
  {% block metadata %}
  <meta name="description" content="{% block description %}{% endblock %}">
  <meta name="author" content="{% block author %}Oliver Peng{% endblock %}">
  <meta name="Copyright" content="Copyright Churches Helping Churches 2012. All Rights Reserved.">
  {% endblock %}

  {# Mobile viewport optimized: j.mp/bplateviewport #}
  {% block mobile_viewport_optimization %}
  {# <meta name="viewport" content="width=device-width, initial-scale=1.0"> #}
  {% endblock %}

  {% block favicons %}
  {# mathiasbynens.be/notes/touch-icons #}
  {# For iPhone 4 with high-resolution Retina display: #}
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ STATIC_URL }}img/favicons/apple-touch-icon-114x114-precomposed.png">
  {# For first-generation iPad: #}
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ STATIC_URL }}img/favicons/apple-touch-icon-72x72-precomposed.png">
  {# For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: #}
  <link rel="apple-touch-icon-precomposed" href="{{ STATIC_URL }}img/favicons/apple-touch-icon-precomposed.png">
  <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicons/favicon.ico">
  {% endblock %}

  {% block css %}
  {# CSS: implied media="all" #}
  <link rel="stylesheet" href="{% get_static_prefix %}css/style.css">
  {% endblock %}
  {% block extra_css %}{% endblock %}

  {# More ideas for your <head> here: h5bp.com/docs/#head-Tips #}

  {% block head_js %}
  {% comment %}
  All JavaScript at the bottom, except for Modernizr and Respond.
  Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
  For optimal performance, use a custom Modernizr build:
  www.modernizr.com/download/
  {% endcomment %}
  {# modernizr and respond are also only loaded in the head for IE, else they are included in main.js at the end #}
  <script src="{{ STATIC_URL }}js/libs/modernizr-2.0.6.min.js"></script>
  {% endblock %}
  {% block extra_head %}{% endblock %}
</head>
{% endblock %}

{% block body %}
<body>
  <div id="wrapper">

    {% block header %}
    <header>
      {% block navigation %}<nav></nav>{% endblock %}
    </header>
    {% endblock %}

    <div id="main" role="main" class="clearfix">
      {% block content %}
      {% endblock %}
    </div>
    <div class="push"></div>
  </div>

  {% block footer %}
  <footer>

  </footer>
  {% endblock %}
  
  {% block js %}
  {# JavaScript at the bottom for fast page loading #}
  {# Javascript files are all concatenacted and compressed #}
  {# to update for production use python manage generatemedia #}
  <script src="{{ STATIC_URL }}js/libs/jquery-1.6.2.min.js"></script>
  <script src="{{ STATIC_URL }}js/global.js"></script>
  <script src="{{ STATIC_URL }}js/libs/cufon-yui.js"></script>
  <script src="{{ STATIC_URL }}js/libs/cufon-fonts/NillandRegular.font.js"></script>
  <script type="text/javascript">
      Cufon.replace('h1, h2, h3, h4, h5, h6, #slider .navigation a, .btn-link');
  </script>
  {% endblock %}
  {% block extra_js %}{% endblock %}

  {% block google_analytics %}
  {% if not request.user.is_superuser %}
  {# mathiasbynens.be/notes/async-analytics-snippet Change UA-XXXXX-X to be your site's ID #}
  <script>
    var _gaq=[['_setAccount','{% block analytics_id %}UA-20445819-1{% endblock %}'],['_trackPageview'],['_trackPageLoadTime']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
  {% endif %}
  {% endblock %}

</body>
{% endblock %}
</html>

django/chc/templates/churches.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Churches Helping Churches - The Churches{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/churches.css">
{% endblock %}

{% block extra_js %}
<script>
$(document).ready(function() {
    $('.left, .right')
        .css('cursor', 'pointer')
        .click( function() {
            var href = $(this).find('a').attr('href');
            if (href) {
                window.location.href = href;
            }
        });
});
</script>
{% endblock %}

{% block nav-churches %}<strong>The Churches</strong>{% endblock %}

{% block content %}
<h2 class="first">The Churches</h2>

<div>
    <iframe src="https://batchgeo.com/map/437bb8c40bec2e064f95ee5462fe2296" width="100%" height="500" frameborder="0" style="border:1px solid #aaa;border-radius:10px;overflow:hidden;"></iframe>
</div>

<h2>Churches Helped</h2>

<div class="shadow clearfix helped">
    <div class="left">
        <img src="{{ STATIC_URL }}img/churches/haiti.png">
        <div class="link-wrapper">
            <a class="btn-link" href="{% url what-we-do.projects %}#haiti">In Haiti</a>
        </div>
    </div>
    <div class="right">
        <img src="{{ STATIC_URL }}img/churches/japan.png">
        <div class="link-wrapper">
            <a class="btn-link" href="{% url what-we-do.projects %}#japan">In Japan</a>
        </div>
    </div>
</div>

{% endblock %}

django/chc/templates/give.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Churches Helping Churches - Give{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% get_static_prefix %}css/give.css">
{% endblock %}

{% block nav-give %}<strong>Give</strong>{% endblock %}

{% block content %}
<article>
    <h2>Give</h2>

    <div class="shadow clearfix">
        <a class="btn-link big" href="https://donate.churcheshelpingchurches.com/">Credit Card or Check</a>
        <a class="btn-link big" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=69Y8M5YWHS28J" rel="nofollow">PayPal</a>
        <a class="btn-link big" href="http://www.canadahelps.org/CharityProfilePage.aspx?CharityID=d99876" rel="nofollow">Canadian Donors</a>

        <div class="left">
            <p class="big">
                Thank you for your interest in Churches Helping Churches. God will use the generous support of people like you to meet the needs of the churches in need.
            </p>
            <p>
                Thank you for your willingness to be used for such a time as this. We will put your gift to careful use. We pray that God will use His Word to strengthen and encourage the faith of the people in these disaster-affected areas and of the global Church as we respond to these crises.
                <br><br>
                God bless you for your generosity.
            </p>
            <p class="by">— Pastors Mark Driscoll and James MacDonald<br>for Churches Helping Churches</p>
        </div>

        <div class="right">
            <p>
                Need help with your gift?<br>
                <a href="mailto:information@churcheshelpingchurches.com">Send us an email</a>!<br><br>

                Churches Helping Churches is a 501(c)(3) Registered Charity <br>
                27-1747541<br><br>

                Churches Helping Churches<br>
                P.O. Box 6558<br>
                Elgin, IL 60121-6558
            </p>
        </div>
    </div>
</article>


{% endblock %}

django/chc/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Churches Helping Churches{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% get_static_prefix %}css/home.css">
{% endblock %}

{% block extra_js %}
<script src="{{ STATIC_URL }}js/libs/jquery.jsmovie.1.4.2.js"></script>
<script src="{{ STATIC_URL }}js/home.js"></script>
{% endblock %}

{% block content %}
{% get_static_prefix as STATIC_PREFIX %}
<section>
	<h2 hidden>Home</h2>

	<article class="clearfix">
		<div class="left">
			<h3>Over 400 churches<br><span>in a global partnership.</span></h3>
			<a class="btn-link big" id="join-btn" href="{% url give %}"><div id="pulse"></div>Give Now</a>
		</div>
		<div class="right">
			<iframe width="542" height="304" src="http://www.youtube.com/embed/NUImAxFpy3c?rel=0&modestbranding=1&showinfo=0&autoplay=1" frameborder="0" allowfullscreen></iframe>
		</div>
	</article>

	<aside class="featured-box shadow">
		<div class="constrain">
			<img src="{{STATIC_PREFIX}}img/home/chcupdate2012.png">
			<h3>Download CHC Update</h3>
			<p class="subtext"></p>
			
			<div class="featured-content">
				<p>Download the 2012 CHC Update video by clicking on the button below and share this with your church or group! Thank you for your support!</p>
			</div>
		</div>
		<div class="featured-link-wrapper">
			<a class="btn-link" href="http://dl.dropbox.com/u/46927368/Videos/CHC_6_H264.mov?dl=1">Download Video</a>
		</div>
	</aside>

	<aside class="featured-box shadow">
		<div class="constrain">
			<img src="{{STATIC_PREFIX}}img/home/20120717_blog.png">
			<h3>You Can Help</h3>
			<p class="subtext"></p>

			<div class="featured-content">
				<p>We want to finish strong. With your help we can do it together. Large or small, every gift counts towards rebuilding the church!</p>
			</div>
		</div>
		<div class="featured-link-wrapper">
			<a class="btn-link" href="/blog/2012/07/19/finishing-strong/">Learn More</a>
		</div>
	</aside>

	<aside class="featured-box shadow">
		<div class="constrain">
			<img src="{{STATIC_PREFIX}}img/home/featured-3.jpg">
			<h3>Photos, Videos &amp; More</h3>
			<p class="subtext">Featured Media</p>
			
			<div class="featured-content">
				<ul class="square">
					<li>Video: <a target="_blank" href="http://www.youtube.com/watch?v=m6MFtTcpS68&feature=player_embedded">Interview with Pastor Yoshi Ohari</a></li>
					<li>Photos: <a target="_blank" href="http://www.flickr.com/photos/churcheshelpingchurches/">CHP Miyagi, February 2012</a></li>
				</ul>
			</div>
		</div>
		<div class="featured-link-wrapper">
			<a class="btn-link" href="{% url media %}">View more</a>
		</div>
	</aside>
</section>
{% endblock %}

django/chc/templates/join/pray.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Churches Helping Churches - Pray Online{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% get_static_prefix %}css/join.css">
{% endblock %}

{% block nav-join %}<a class="active" href="{% url join %}">Join</a>{% endblock %}

{% block content %}
{% get_static_prefix as STATIC_PREFIX %}
<h2>Pray Online</h2>

{% endblock %}

django/chc/templates/join/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Churches Helping Churches - Sign Up{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% get_static_prefix %}css/join/signup.css">
{% endblock %}

{% block extra_js %}
<script src="{% get_static_prefix %}js/libs/jquery.validate.js"></script>
<script src="{% get_static_prefix %}js/signup.js"></script>
{% endblock %}

{% block nav-join %}<a class="active" href="{% url join %}">Join</a>{% endblock %}

{% block content %}
{% get_static_prefix as STATIC_PREFIX %}
<h2>Sign Up</h2>

{% if error_msgs %}
<ul class="error">
	{% for err in error_msgs %}
	<li>{{ err }}</li>
	{% endfor %}
</ul>
{% endif %}

<form id="signup-form" method="post">
	{% csrf_token %}
	{{ form.non_field_errors }}

	<h3>Please fill out your information.</h3>
	<span class="highlight">* indicates required field</span>
	<div class="clearfix">
		<div class="fieldWrapper lcol">
			<label for="id_fname">First Name <span class="highlight">*</span></label>
			{{ form.fname }}
			{{ form.fname.errors }}
		</div>
		<div class="fieldWrapper rcol">
			<label for="id_lname">Last Name <span class="highlight">*</span></label>
			{{ form.lname }}
			{{ form.lname.errors }}
		</div>
	</div>
	<div class="fieldWrapper">
		{{ form.city.label_tag }}
		{{ form.city }}
		{{ form.city.errors }}
	</div>
	<div class="clearfix">
		<div class="fieldWrapper state lcol">
			{{ form.state.label_tag }}
			{{ form.state }}
			{{ form.state.errors }}
		</div>
		<div class="fieldWrapper country rcol">
			{{ form.country.label_tag }}
			{{ form.country }}
			{{ form.country.errors }}
		</div>
	</div>
	<div class="clearfix">
		<div class="fieldWrapper email lcol">
			<label for="id_email">Email Address <span class="highlight">*</span></label>
			{{ form.email }}
			{{ form.email.errors }}
		</div>
		<div class="fieldWrapper phone rcol">
			{{ form.phone.label_tag }}
			{{ form.phone }}
			{{ form.phone.errors }}
		</div>
	</div>
	<div class="fieldWrapper">
		<label for="id_church_name">Church Name <span class="highlight church_name">*</span></label>
		{{ form.church_name }}
		{{ form.church_name.errors }}
	</div>
	<div class="fieldWrapper checkbox">
		{{ form.is_pastor }} {{ form.is_pastor.label_tag }}
		{{ form.is_pastor.errors }}
	</div>
	<div class="fieldWrapper">
		{{ form.church_website.label_tag }}
		{{ form.church_website }}
		{{ form.church_website.errors }}
	</div>

	<h3 class="second">Please select one or more of the following responses:</h3>
	<div class="fieldWrapper checkbox">
		{{ form.take_offering }} {{ form.take_offering.label_tag }}
		{{ form.take_offering.errors }}
	</div>
	<div class="fieldWrapper checkbox">
		{{ form.will_contribute }} {{ form.will_contribute.label_tag }}
		{{ form.will_contribute.errors }}
	</div>
	<div class="fieldWrapper checkbox">
		{{ form.receive_updates }} {{ form.receive_updates.label_tag }}
		{{ form.receive_updates.errors }}
	</div>
    <p><input type="submit" class="btn-link" value="Sign Up" /></p>
</form>

{% endblock %}

django/chc/templates/where-we-are.html
{% extends 'base.html' %}

{% block title %}Churches Helping Churches - Where We Are{% endblock %}

{% block nav-where-we-are %}<strong>Where We Are</strong>{% endblock %}

{% block content %}
<h1>Where We Are</h1>
{% endblock %}